openapi: 3.0.1
info:
  title: '@jupiterone/graph-microsoft-endpoint-defender'
  description: A JupiterOne Integration for Microsoft Defender for Endpoint
  x-cortex-git:
    github:
      repository: JupiterOne/graph-microsoft-endpoint-defender
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-microsoft-endpoint-defender'
